Fs=1000;
Fd=100;
NFFT=1;
b=round(rand(1,1000));
bnrz=kutuplu(b,Fd,Fs,'nrz');
[gsybnrz,f]=pwelch(bnrz,[],NFFT,Fs);
plot(f,gsybnrz,'k');
title('kutuplu NRZ Güç Spektral Yoğunluğu');
pause;
brz=kutuplu(b,Fd,Fs,'rz');
[gsybrz,f]=pwelch(brz,[],NFFT,Fs);
plot(f,gsybrz,'k');
title('kutuplu RZ NGüç Spektral Yoğunluğu');